version: 2

sources:
  - name: raw
    database: "{{ env_var('GCP_PROJECT_ID') }}"
    schema: tourism_raw
    tables:
      - name: tourist_accommodations
      - name: tourist_age_sex
      - name: tourist_revenue
